services:
  api:
    build:
      context: ./rest-api-mvp-arquitetura-software
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000

  web:
    build:
      context: ./frontend-mvp-arquitetura-software
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - api